import mongoose from "mongoose";

const analysisSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    resumeText: {
      type: String,
      required: true,
    },
    jobDescription: {
      type: String,
      default: "",
    },
    analysisResult: {
      type: Object,
      required: true,
    },
    resumeLabel: {
      type: String,
      default: "",
    },
    jobLabel: {
      type: String,
      default: "",
    },
    originalFileName: {
      type: String,
      default: "",
    },
    // Deterministic hash of resume content to avoid duplicate processing
    hash: {
      type: String,
      index: true,
    },
    // Top-level numeric score (0-100)
    score: {
      type: Number,
      default: null,
    },
    // Suggestions generated by Groq (LLM) or empty array
    suggestions: {
      type: [String],
      default: [],
    },
    // Missing skills inferred from job description not found in resume
    missingSkills: {
      type: [String],
      default: [],
    },
  },
  {
    timestamps: true,
  }
);

const Analysis = mongoose.model("Analysis", analysisSchema);

export default Analysis;